<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bantuan 247_top-menu__chevron</name>
   <tag></tag>
   <elementGuidId>da445f6e-526e-4702-a2d9-e84f6b34b179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='Arrow down'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Arrow down</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgZmlsbD0iI2ZmZiI+PHBhdGggZD0iTTUuMSA4LjgzYzAgLjI0LjEuNDguMjguNjZsNS42NyA1LjZhLjk1Ljk1IDAgMCAwIDEuMzQgMGw1LjY3LTUuNmMuMzctLjM3LjM3LS45NiAwLTEuMzJzLS45Ny0uMzctMS4zNCAwbC01IDQuOTQtNS00Ljk0YS45NS45NSAwIDAgMC0xLjM0IDAgLjkzLjkzIDAgMCAwLS4yNy42NnoiLz48L3N2Zz4K</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-menu__chevron</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[1]/header[@class=&quot;header&quot;]/div[@class=&quot;header__top&quot;]/div[@class=&quot;top-menu&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;left-section&quot;]/div[@class=&quot;item&quot;]/div[@class=&quot;top-menu&quot;]/img[@class=&quot;top-menu__chevron&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Arrow down'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img[2]</value>
   </webElementXpaths>
</WebElementEntity>
